### PR TITLE
Update to SQ 9.9, Erlang 26 and add Docker based build process

### PR DESCRIPTION
**Pull request by gbence**
* Add parser rules to support map comprehensions, that were introduced in Erlang 26,
* Also add @mpope9's fix to handle records with atom keys,
* Update docs and build processes to support SonarQube 9.9 (LTS),
* Add Docker based build process to let developers keep their developer environment clean and Java free. 😈
* Also add sensor to manage Elvis output.
* Refactor relative/absolute path management in config.

### CODE REVIEW

**Comment by apetrelli** [comment]
Good job! However it seems that this repository is dead. Do you consider releasing your fork by yourself?

**Comment by vooolll** [comment]
@apetrelli @gbence we a planning to bring plugin back, so I am going to approve this mr asap

**Comment by gbence** [comment]
:champagne: thx.

**Comment by vooolll** [comment]
@gbence for some reason build is failed , checking out why we have:
`Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar (default-cli) on project erlang: Could not find a default branch for project with key 'evolution-gaming_sonar-erlang'. Make sure project exists. -> [Help 1]
`

**Comment by gbence** [comment]
Honestly, I've never built this project barely using Maven, without Docker, so I have no experience with Maven 3.10.

The build process still works with `maven:3.9.3-amazoncorretto-17-debian` (currently in the `Dockerfile`) and it also works with a recent `maven:3.9.6-amazoncorretto-21-debian`.  Unfortunately there is (still) no prebuilt Maven 3.10 image, so I cannot easily try that.

@vooolll: Can you please help me understanding the context of your failing build?  On what OS (and distro), what libc, Java, Maven, etc. have you tried building the project?

**Comment by vooolll** [comment]
@gbence so basically what build does, it runs 
`mvn clean -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar`

under ubuntu-latest and java 11

workflow file:

```
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
```

**Pull request merged**
